add 'schedule' option to allow cron scheduling
logstash-plugins/logstash-input-exec pull request #14
Opened 2018-01-11 22:54 UTC by fbaligand

Like jdbc input plugin, it allows to schedule command execution using cron syntax.
This is particularly useful when you need to execute command each day at a specific hour.

2018-01-19 16:50 UTC, jsvd requested changes
minor cosmetic change otherwise LGTM

2018-01-19 16:50 UTC, jsvd commented on lib/logstash/inputs/exec.rb
> +          @scheduler = Rufus::Scheduler.new(:max_work_threads => 1)
can we reindent this to two spaces?

2018-01-20 08:59 UTC, fbaligand commented
Hi @jsvd
Damn, I was near from a "perfect" :)
I fixed indentation to 2 spaces !

=> Is it OK to merge ?

2018-01-24 22:12 UTC, fbaligand commented
Hi @jsvd,
Could you merge the PR and release the plugin ?

2018-02-02 14:54 UTC, fbaligand commented
Hi @jsvd,
Could you merge the PR and release the plugin ?

2018-02-09 02:35 UTC, rkhapre commented
Hi please let me know if this is available to use?

2018-02-09 06:00 UTC, fbaligand commented
Hi @rkhapre,

It will be available when it will be merged and released. 

That said, if you don’t want to wait, you can get an unofficial release here : 
https://github.com/fbaligand/logstash-input-exec/releases/download/v3.2.0/logstash-input-exec-3.2.0.gem

2018-02-09 08:36 UTC, rkhapre commented
Hi Installed this gem with logstash 5.2.2 version 

`logstash-5.2.2\vendor\jruby\bin>gem install logstash-input-exec-3.2.0.gem`

It got installed successfully, but when i run my conf file it gives me error

```
input {
  exec {
  command => "xyz...."
  schedule => { cron => "48 13 * * *"}
  }
}
```
Below is the error, it is not able to identify schedule key

```
fig_file=>"F:/logstash-5.2.2/bin/Scheduler.conf"}
13:47:12.545 [LogStash::Runner] DEBUG logstash.plugins.registry - On demand addi
ng plugin to the registry {:name=>"exec", :type=>"input", :class=>LogStash::Inpu
ts::Exec}
13:47:12.545 [LogStash::Runner] ERROR logstash.inputs.exec - Unknown setting 'sc
hedule' for exec
13:47:12.555 [LogStash::Runner] ERROR logstash.agent - Cannot load an invalid co
nfiguration {:reason=>"Something is wrong with your configuration.", :backtrace=
```

2018-02-09 08:51 UTC, fbaligand commented
The right syntax is : `schedule => "48 13 * * *"`

2018-02-09 09:30 UTC, rkhapre commented
Yes i have tried this as well, with this also i am getting same error.
Please suggest some other way to install the whole plugin...

I have also tried to get full installation from this location
https://github.com/fbaligand/logstash-input-exec/tree/v3.2.0

Downloaded the zip, but unable to do offline installation, i tried this command
`
bin/logstash-plugin install file:///F:/LOgstash_Exec_File/logstash-input-exec-3.2.0.zip`

I get this error

```
ERROR: Invalid pack for: file:///F:/LOgstash_Exec_File/logstash-input-exec-3.2.0
.zip, reason: The pack must contains at least one plugin, message: The pack must
 contains at least one plugin
```

2018-02-09 09:52 UTC, fbaligand commented
The right way to install the plugin :
bin/logstash-plugin install file:///path/to/logstash-input-exec-3.2.0.gem (not zip file)

2018-02-09 10:35 UTC, rkhapre commented
Hi

Thanks for reply. I have tried both, below is the error i get

```
F:\logstash-5.2.2\bin>logstash-plugin install file:///F:/LOgstash_Exec_File/logs
tash-input-exec-3.2.0.gem
ERROR: Invalid pack for: file:///F:/LOgstash_Exec_File/logstash-input-exec-3.2.0
.gem, reason: Invalid format, the pack must be in zip format, message: Invalid f
ormat, the pack must be in zip format
```

```
F:\logstash-5.2.2\bin>logstash-plugin install file:///F:/LOgstash_Exec_File/logs
tash-input-exec-3.2.0.zip
Installing file: /F:/LOgstash_Exec_File/logstash-input-exec-3.2.0.zip
ERROR: Invalid pack for: file:///F:/LOgstash_Exec_File/logstash-input-exec-3.2.0
.zip, reason: The pack must contains at least one plugin, message: The pack must
 contains at least one plugin
```

2018-02-09 10:45 UTC, fbaligand commented
OK, so put .gem file into `logstash/bin` directory.
And launch : `logstash-plugin install logstash-input-exec-3.2.0.gem`

2018-02-09 11:39 UTC, rkhapre commented
Hi

This is working like a charm, now schedule is also working very well
Thanks a lot

2018-02-09 11:54 UTC, fbaligand commented
Great !
Happy to see you enjoy this new feature !

2018-02-14 17:06 UTC, fbaligand commented
Hi @jsvd,
Could you merge the PR and release the plugin ?

2018-02-26 16:39 UTC, fbaligand commented
@jsvd @ph @suyograo @colinsurprenant @purbon 
Please, could someone review this PR ?

I fixed the very little change requested by @jsvd (1 month ago). 
=> normally, it’s OK to merge.

2018-02-27 19:15 UTC, colinsurprenant commented
@fbaligand I am sorry this PR did not get attention recently. Please avoid spamming random individuals to raise awareness, most of the people you mentioned are not involved at all with this and it is extremely annoying to receive spammy notifications like that.

2018-02-27 20:18 UTC, fbaligand commented
Hi @colinsurprenant ,

I understand this kind of multi-notification could be annoying. 
Be assured I do that as a last resort after more than one month without feedback. 
That’s why I’m very sad if it feels like spam... :(

2018-02-27 20:40 UTC, jsvd approved these changes
LGTM
apologies for the lack of response, I've been away for a month on paternity leave.

2018-02-27 20:41 UTC, merged

2018-02-28 06:52 UTC, fbaligand commented
@jsvd 
Wow, congratulations for your paternity!
I wish you lots of happiness!

And big thanks for the merge !

2018-03-01 17:02 UTC, fbaligand commented
Hi @jsvd,

Now you merged this feature, could you release logstash-input-exec plugin ?

Thanks in advance!
Fabien

2018-03-01 22:24 UTC, jsvd commented
[version 3.2.0 has been published](https://github.com/logstash-plugins/logstash-input-exec/compare/v3.2.0)

2018-03-02 06:28 UTC, fbaligand commented
Great ! Thanks @jsvd !